Numpy Arrays

In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(3) # An array of zeros

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(3) # An array of ones

array([1., 1., 1.])

In [12]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [14]:
np.eye(4) # Generates an identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.17543055, 0.36405888, 0.86113748, 0.9760486 , 0.11934239])

In [16]:
np.random.rand(5,5)

array([[0.60881082, 0.36907814, 0.64363537, 0.20217307, 0.66116405],
       [0.99108833, 0.72576361, 0.40116423, 0.8204191 , 0.797636  ],
       [0.23407199, 0.95434276, 0.04439701, 0.78871759, 0.57917516],
       [0.977769  , 0.17197577, 0.53532398, 0.13915866, 0.04514838],
       [0.05425869, 0.67443961, 0.22765918, 0.46005098, 0.95049545]])

In [17]:
np.random.randint(1,100)

70

In [18]:
arr=np.linspace(0,100,25)
arr.reshape(5,5)

array([[  0.        ,   4.16666667,   8.33333333,  12.5       ,
         16.66666667],
       [ 20.83333333,  25.        ,  29.16666667,  33.33333333,
         37.5       ],
       [ 41.66666667,  45.83333333,  50.        ,  54.16666667,
         58.33333333],
       [ 62.5       ,  66.66666667,  70.83333333,  75.        ,
         79.16666667],
       [ 83.33333333,  87.5       ,  91.66666667,  95.83333333,
        100.        ]])

In [19]:
arr.max()

100.0

In [20]:
arr.min()

0.0

In [21]:
arr.argmax() # It returns the index of maximum value in an array

24

In [22]:
arr.argmin() # It returns the index of minimmum value in an array

0

In [23]:
arr.reshape(5,5).shape

(5, 5)